# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_auto_20160404_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(default='São Gonçalo do Amarante', max_length=50, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='person',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='person',
            name='indication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voters.Person', verbose_name='Indicação'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='telefone secundario'),
        ),
    ]
