# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0004_auto_20160412_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='cpf',
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(default='São Gonçalo do Amarante', max_length=50, verbose_name='cidade de residência'),
        ),
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.CharField(max_length=50, verbose_name='Bairro de residência'),
        ),
        migrations.AlterField(
            model_name='person',
            name='number',
            field=models.CharField(max_length=6, verbose_name='número de residência'),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.CharField(default='RN', max_length=2, verbose_name='estado de residência'),
        ),
        migrations.AlterField(
            model_name='person',
            name='street',
            field=models.CharField(max_length=50, verbose_name='rua de residência'),
        ),
    ]
