# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-16 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0004_auto_20160525_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='veiculo',
        ),
        migrations.AddField(
            model_name='person',
            name='qnt_combustivel',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Combustível'),
        ),
        migrations.AddField(
            model_name='person',
            name='qnt_veiculo',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Veículos'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(default='São Gonçalo do Amarante', max_length=50, verbose_name='Cidade de residência'),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.CharField(default='RN', max_length=2, verbose_name='UF de residência'),
        ),
        migrations.AlterField(
            model_name='person',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Rua/Nº de residência'),
        ),
    ]
