# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-16 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0005_auto_20160616_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, verbose_name='Usuário do Facebook'),
        ),
    ]
