# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cellphone',
            field=models.CharField(default=datetime.datetime(2016, 4, 4, 15, 13, 9, 849117, tzinfo=utc), max_length=15, verbose_name='celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default=datetime.datetime(2016, 4, 4, 15, 13, 22, 632958, tzinfo=utc), max_length=50, verbose_name='cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='cpf',
            field=models.CharField(default=datetime.datetime(2016, 4, 4, 15, 13, 28, 128961, tzinfo=utc), max_length=15, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='district',
            field=models.CharField(default=datetime.datetime(2016, 4, 4, 15, 13, 31, 632879, tzinfo=utc), max_length=50, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default=datetime.datetime(2016, 4, 4, 15, 13, 33, 400854, tzinfo=utc), max_length=50, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='facebook',
            field=models.URLField(default=datetime.datetime(2016, 4, 4, 15, 13, 35, 304917, tzinfo=utc), verbose_name='facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='number',
            field=models.CharField(default=datetime.datetime(2016, 4, 4, 15, 13, 39, 771022, tzinfo=utc), max_length=6, verbose_name='número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default=datetime.datetime(2016, 4, 4, 15, 13, 41, 416883, tzinfo=utc), max_length=15, verbose_name='telefone secundario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.CharField(default='RN', max_length=2, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='person',
            name='street',
            field=models.CharField(default=datetime.datetime(2016, 4, 4, 15, 13, 43, 18666, tzinfo=utc), max_length=50, verbose_name='rua'),
            preserve_default=False,
        ),
    ]
